a = int(input("inserisci un numero: "))
b = int(input("inserisci un numero: "))
somQ = ((a*a)+(b*b))
qSom = ((a + b)**2)
diffQ = ((a*a)-(b*b))
qDiff = ((a - b)**2)
lista = (somQ, qSom, diffQ, qDiff)
print(lista)